name: PM25
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - absl-py=1.4.0
  - affine=2.4.0
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - alsa-lib=1.2.8
  - aom=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attr=2.5.1
  - attrs=23.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.2
  - bleach=6.0.0
  - blinker=1.6.2
  - blosc=1.21.4
  - boost-cpp=1.78.0
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-blosc2=2.9.2
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.0
  - cairo=1.16.0
  - certifi=2024.8.30
  - cffi=1.15.1
  - cfitsio=4.2.0
  - charls=2.4.2
  - charset-normalizer=2.1.1
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.2.1
  - contourpy=1.0.7
  - cryptography=41.0.1
  - cuda=12.1.1
  - cuda-cccl=12.1.109
  - cuda-command-line-tools=12.1.1
  - cuda-compiler=12.1.1
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cudart-static=12.1.105
  - cuda-cuobjdump=12.1.111
  - cuda-cupti=12.1.105
  - cuda-cupti-static=12.1.105
  - cuda-cuxxfilt=12.1.105
  - cuda-demo-suite=12.1.105
  - cuda-documentation=12.1.105
  - cuda-driver-dev=12.1.105
  - cuda-gdb=12.1.105
  - cuda-libraries=12.1.1
  - cuda-libraries-dev=12.1.1
  - cuda-libraries-static=12.1.1
  - cuda-nsight=12.1.105
  - cuda-nsight-compute=12.1.1
  - cuda-nvcc=12.1.105
  - cuda-nvdisasm=12.1.105
  - cuda-nvml-dev=12.1.105
  - cuda-nvprof=12.1.105
  - cuda-nvprune=12.1.105
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvrtc-static=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-nvvp=12.1.105
  - cuda-opencl=12.1.105
  - cuda-opencl-dev=12.1.105
  - cuda-profiler-api=12.1.105
  - cuda-runtime=12.1.1
  - cuda-sanitizer-api=12.1.105
  - cuda-toolkit=12.1.1
  - cuda-tools=12.1.1
  - cuda-version=11.8
  - cuda-visual-tools=12.1.1
  - cudatoolkit=11.8.0
  - cudnn=8.4.1.50
  - curl=8.1.2
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2023.5.0
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - earthpy=0.9.4
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.5.0
  - fftw=3.3.10
  - fiona=1.9.1
  - flatbuffers=22.12.06
  - flit-core=3.9.0
  - folium=0.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.39.4
  - freetype=2.12.1
  - freexl=1.0.6
  - frozenlist=1.3.3
  - fsspec=2023.6.0
  - gast=0.4.0
  - gdal=3.6.2
  - gds-tools=1.6.1.9
  - geopandas=0.13.2
  - geopandas-base=0.13.2
  - geos=3.11.1
  - geotiff=1.7.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.76.3
  - glib-tools=2.76.3
  - gmp=6.2.1
  - google-auth=2.19.1
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpc-cpp=1.51.1
  - grpcio=1.51.1
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.34
  - h5py=3.8.0
  - harfbuzz=6.0.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.4
  - imagecodecs=2023.1.23
  - imageio=2.31.1
  - importlib-metadata=6.6.0
  - importlib-resources=5.12.0
  - importlib_metadata=6.6.0
  - importlib_resources=5.12.0
  - ipython=8.12.2
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.6
  - jack=1.9.22
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json-c=0.16
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.1.2
  - jupyter_console=6.5.1
  - jupyter_core=5.3.0
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.7
  - jxrlib=1.1
  - kealib=1.5.0
  - keras=2.11.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20220623.0
  - libaec=1.0.6
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcublas=12.1.3.1
  - libcublas-dev=12.1.3.1
  - libcublas-static=12.1.3.1
  - libcufft=11.0.2.54
  - libcufft-dev=11.0.2.54
  - libcufft-static=11.0.2.54
  - libcufile=1.6.1.9
  - libcufile-dev=1.6.1.9
  - libcufile-static=1.6.1.9
  - libcups=2.3.3
  - libcurand=10.3.2.106
  - libcurand-dev=10.3.2.106
  - libcurand-static=10.3.2.106
  - libcurl=8.1.2
  - libcusolver=11.4.5.107
  - libcusolver-dev=11.4.5.107
  - libcusolver-static=11.4.5.107
  - libcusparse=12.1.0.106
  - libcusparse-dev=12.1.0.106
  - libcusparse-static=12.1.0.106
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=13.1.0
  - libgcrypt=1.10.1
  - libgdal=3.6.2
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.76.3
  - libgomp=13.1.0
  - libgpg-error=1.46
  - libgrpc=1.51.1
  - libiconv=1.17
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libnetcdf=4.9.1
  - libnghttp2=1.52.0
  - libnpp=12.1.0.40
  - libnpp-dev=12.1.0.40
  - libnpp-static=12.1.0.40
  - libnsl=2.0.0
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.2.0.2
  - libnvjpeg-dev=12.2.0.2
  - libnvjpeg-static=12.2.0.2
  - libnvvm-samples=12.1.105
  - libogg=1.3.4
  - libopenblas=0.3.23
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.2
  - libprotobuf=3.21.12
  - librttopo=1.1.0
  - libsndfile=1.2.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libsystemd0=252
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxgboost=1.7.6
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvmlite=0.40.0
  - locket=1.0.0
  - lz4-c=1.9.4
  - mapclassify=2.5.0
  - markdown=3.4.3
  - markupsafe=2.1.3
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mistune=2.0.5
  - mpg123=1.31.3
  - multidict=6.0.4
  - munch=3.0.0
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nbclient=0.8.0
  - nbconvert=7.5.0
  - nbconvert-core=7.5.0
  - nbconvert-pandoc=7.5.0
  - nbformat=5.9.0
  - nccl=2.17.1.1
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=3.1
  - notebook=6.1.6
  - nsight-compute=2023.1.1.4
  - nspr=4.35
  - nss=3.89
  - numba=0.57.0
  - numpy=1.24.3
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openssl=3.1.3
  - opt_einsum=3.3.0
  - packaging=23.1
  - pandas=1.5.3
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.4.0
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.1.2
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.5.1
  - ply=3.11
  - pooch=1.7.0
  - poppler=23.03.0
  - poppler-data=0.4.12
  - postgresql=15.2
  - proj=9.1.1
  - prometheus_client=0.17.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - protobuf=4.21.12
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pure_eval=0.2.2
  - py-xgboost=1.7.6
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.15.1
  - pyjwt=2.7.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyproj=3.5.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.8.17
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.17.1
  - python-flatbuffers=23.5.26
  - python_abi=3.8
  - pytz=2023.3
  - pyu2f=0.1.5
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=25.1.0
  - qt-main=5.15.8
  - qtconsole=5.4.3
  - qtconsole-base=5.4.3
  - qtpy=2.3.1
  - rasterio=1.3.6
  - re2=2022.06.01
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - rtree=1.0.1
  - scikit-image=0.19.3
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - send2trash=1.8.2
  - setuptools=67.7.2
  - shapely=2.0.1
  - sip=6.7.9
  - six=1.16.0
  - snappy=1.1.10
  - snuggs=1.4.7
  - soupsieve=2.3.2.post1
  - sqlite=3.42.0
  - stack_data=0.6.2
  - tensorboard=2.11.2
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.11.0
  - tensorflow-base=2.11.0
  - tensorflow-estimator=2.11.0
  - termcolor=2.3.0
  - terminado=0.13.3
  - threadpoolctl=3.1.0
  - tifffile=2023.4.12
  - tiledb=2.13.2
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=5.1.1
  - traitlets=5.9.0
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzcode=2023c
  - tzdata=2023c
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - werkzeug=2.3.4
  - wheel=0.40.0
  - widgetsnbextension=4.0.7
  - wrapt=1.15.0
  - xarray=2023.1.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xerces-c=3.2.4
  - xgboost=1.7.6
  - xkeyboard-config=2.38
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2023.5.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.2
  - zeromq=4.3.4
  - zfp=1.0.0
  - zipp=3.15.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.2
  - pip:
      - attention==5.0.0
      - comm==0.1.3
      - ipykernel==6.23.2
      - keract==4.5.1
      - pyaml==23.9.7
      - scikit-optimize==0.9.0